workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gaec.maferme
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FIREBASE_API_KEY: $FIREBASE_API_KEY
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        FIREBASE_MESSAGING_SENDER_ID: $FIREBASE_MESSAGING_SENDER_ID
        FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
        FIREBASE_STORAGE_BUCKET: $FIREBASE_STORAGE_BUCKET
        APP_STORE_CONNECT_API_KEY: $APP_STORE_CONNECT_API_KEY
        APP_STORE_CONNECT_API_KEY_ID: $APP_STORE_CONNECT_API_KEY_ID
        APP_STORE_CONNECT_API_ISSUER_ID: $APP_STORE_CONNECT_API_ISSUER_ID
        BUNDLE_ID: "com.gaec.maferme"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up code signing settings
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install pods
        script: |
          cd ios
          pod install
      - name: Update Firebase config
        script: |
          cd ios/Runner
          sed -i '' "s/\${FIREBASE_API_KEY}/$FIREBASE_API_KEY/g" GoogleService-Info.plist
          sed -i '' "s/\${FIREBASE_APP_ID}/$FIREBASE_APP_ID/g" GoogleService-Info.plist
          sed -i '' "s/\${FIREBASE_MESSAGING_SENDER_ID}/$FIREBASE_MESSAGING_SENDER_ID/g" GoogleService-Info.plist
          sed -i '' "s/\${FIREBASE_PROJECT_ID}/$FIREBASE_PROJECT_ID/g" GoogleService-Info.plist
          sed -i '' "s/\${FIREBASE_STORAGE_BUCKET}/$FIREBASE_STORAGE_BUCKET/g" GoogleService-Info.plist
      - name: Flutter build
        script: |
          flutter build ios --release \
            --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY \
            --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID \
            --dart-define=FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID \
            --dart-define=FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID \
            --dart-define=FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
      - name: Run tests
        script: |
          flutter test
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - ${NOTIFICATION_EMAIL}
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_API_KEY_ID
        issuer_id: $APP_STORE_CONNECT_API_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Testeurs internes
        submit_to_app_store: false 