workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      vars:
        FIREBASE_API_KEY: $FIREBASE_API_KEY
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        FIREBASE_MESSAGING_SENDER_ID: $FIREBASE_MESSAGING_SENDER_ID
        FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
        FIREBASE_STORAGE_BUCKET: $FIREBASE_STORAGE_BUCKET
        BUNDLE_ID: "com.gaec.maferme"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Clean build environment
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Precache Flutter and fetch packages
        script: |
          flutter pub get
          flutter precache --ios

      - name: Generate iOS frameworks (fixes Flutter.h not found)
        script: |
          flutter build ios-framework --no-universal --output=build/ios-framework

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Replace Firebase values in plist
        script: |
          cd ios/Runner
          plutil -replace API_KEY -string "$FIREBASE_API_KEY" GoogleService-Info.plist
          plutil -replace GOOGLE_APP_ID -string "$FIREBASE_APP_ID" GoogleService-Info.plist
          plutil -replace GCM_SENDER_ID -string "$FIREBASE_MESSAGING_SENDER_ID" GoogleService-Info.plist
          plutil -replace PROJECT_ID -string "$FIREBASE_PROJECT_ID" GoogleService-Info.plist
          plutil -replace STORAGE_BUCKET -string "$FIREBASE_STORAGE_BUCKET" GoogleService-Info.plist
          cd ../..

      - name: Build iOS release
        script: |
          flutter build ios --release --no-codesign

      - name: Run Flutter tests
        script: |
          flutter test

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - cytech.gaec@gmail.com
