workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.gaec.maferme
      flutter: stable
      xcode: latest
      vars:
        FIREBASE_API_KEY: $FIREBASE_API_KEY
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        FIREBASE_MESSAGING_SENDER_ID: $FIREBASE_MESSAGING_SENDER_ID
        FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
        FIREBASE_STORAGE_BUCKET: $FIREBASE_STORAGE_BUCKET
        BUNDLE_ID: "com.gaec.maferme"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Flutter clean
        script: |
          flutter clean

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Precache Flutter dependencies for iOS
        script: |
          flutter precache --ios

      - name: Ensure Flutter.framework (simulator build)
        script: |
          flutter build ios --simulator

      - name: CocoaPods install
        script: |
          cd ios
          rm -rf Pods Podfile.lock Runner.xcworkspace
          pod install --repo-update
          cd ..

      - name: Update Firebase plist values
        script: |
          cd ios/Runner
          plutil -replace API_KEY -string "$FIREBASE_API_KEY" GoogleService-Info.plist
          plutil -replace GOOGLE_APP_ID -string "$FIREBASE_APP_ID" GoogleService-Info.plist
          plutil -replace GCM_SENDER_ID -string "$FIREBASE_MESSAGING_SENDER_ID" GoogleService-Info.plist
          plutil -replace PROJECT_ID -string "$FIREBASE_PROJECT_ID" GoogleService-Info.plist
          plutil -replace STORAGE_BUCKET -string "$FIREBASE_STORAGE_BUCKET" GoogleService-Info.plist
          cd ../..

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

      - name: Run Flutter tests
        script: |
          flutter test
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - cytech.gaec@gmail.com
      app_store_connect:
        submit_to_testflight: true
        submit_to_app_store: false
