
workflows:
  ios-build:
    name: Build iOS IPA for Maïs Tracker
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Generate Firebase options
        script: flutterfire configure
      - name: Build IPA
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - votre.email@example.com
