workflows:
  ios-workflow:
    name: iOS Build (no codesign)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.gaec.maferme"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"

    scripts:
      - name: Clean build environment
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Precache Flutter and get packages
        script: |
          flutter pub get
          flutter precache --ios

      - name: Build iOS app (no code signing)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - cytech.gaec@gmail.com
