// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3r74pXrjRkxlu2DZJJkrYzXS08meaFnM',
    appId: '1:523429690515:web:4ac046453b91205d2ea166',
    messagingSenderId: '523429690515',
    projectId: 'mais-tracker-app-85823',
    authDomain: 'mais-tracker-app-85823.firebaseapp.com',
    databaseURL: 'https://mais-tracker-app-85823-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mais-tracker-app-85823.firebasestorage.app',
    measurementId: 'G-3426WGMVVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGEbjxiMj_373k5DHdaqJkq4TKw7jv8lg',
    appId: '1:523429690515:android:d783a7d436f2cdef2ea166',
    messagingSenderId: '523429690515',
    projectId: 'mais-tracker-app-85823',
    databaseURL: 'https://mais-tracker-app-85823-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mais-tracker-app-85823.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVboBJq8oxFznuHOjjPvZSIaaCAuD9SR4',
    appId: '1:523429690515:ios:b4b4a3df12fce82e2ea166',
    messagingSenderId: '523429690515',
    projectId: 'mais-tracker-app-85823',
    databaseURL: 'https://mais-tracker-app-85823-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mais-tracker-app-85823.firebasestorage.app',
    iosBundleId: 'com.example.maisTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVboBJq8oxFznuHOjjPvZSIaaCAuD9SR4',
    appId: '1:523429690515:ios:b4b4a3df12fce82e2ea166',
    messagingSenderId: '523429690515',
    projectId: 'mais-tracker-app-85823',
    databaseURL: 'https://mais-tracker-app-85823-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mais-tracker-app-85823.firebasestorage.app',
    iosBundleId: 'com.example.maisTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3r74pXrjRkxlu2DZJJkrYzXS08meaFnM',
    appId: '1:523429690515:web:708e6c582168a5c32ea166',
    messagingSenderId: '523429690515',
    projectId: 'mais-tracker-app-85823',
    authDomain: 'mais-tracker-app-85823.firebaseapp.com',
    databaseURL: 'https://mais-tracker-app-85823-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mais-tracker-app-85823.firebasestorage.app',
    measurementId: 'G-28BDFDS1G9',
  );
}
